version: "3"
services:
  banksystem.rails.postgres.db:
    image: postgres
    volumes:
    -  ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  banksystem.rails.web:
    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    volumes:
    - .:/bank-system
    ports:
    - "3000:3000"
    depends_on:
      - banksystem.rails.postgres.db
